### ISSUE TITLE
help me, I can't make it work, I'm inexperienced.

### ISSUE THREAD

**Issue by lacalos** [PalatinCoder/MMM-GoogleBirthdaysProvider#4]
hi I recently installed MagicMirror and I would like to use your app (or module). I followed what you described and I also looked into various problems. I can't solve. I can say that for example when I try the command from the shell "wget ​​http: // localhost: 8080 / mmm-googlebirthdaysprovider" I get out of connection refused. I checked very well if I had written bad birthdays .. can you help me? I am a newbie in these things and from the day before yesterday I am trying to learn by self-learning. I hope for an answer. thank you so much

**Comment by PalatinCoder** [comment]
Connection refused sounds to me like there is no server listening. Did you start the magicmirror with `npm start`?
Also, there should always be some output on the terminal where you ran npm start. Please create a config.js where MMM-GoogleBirthdaysProvider is the only loaded module, so we don't get spammed with log entries from other modules. (Either create a new config file and backup your current one, or just comment out all other modules). Then run `npm start` again and paste the output here. There should be something that will help us :)

Also, self-learning by experimenting with a project like magic mirror is a great way to get started with Linux, command line, programming and all that stuff. In fact, most of the knowledge and skills I have now I gained this way. It will take time however, so stay at it and it will be worth it ;-)

**Comment by PalatinCoder** [comment]
closed due to inactivity
